/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import com.neu.jdbcapp.model.User;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdbcApp.DatabaseConnector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    JPanel bottomPanel;
    private ArrayList<User> users;
    private User selectedUser;

    public ViewPanel(User inputUser, JPanel bottomPanel) {
        initComponents();
//        this.u = inputUser;
        this.bottomPanel = bottomPanel;
        populateTable();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void populateTable() {
        try {
        this.users = DatabaseConnector.getAllusers();
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount (0);
        for (User u : users) {
        Object[] row = new Object[3];
            row[0] = u.getId();

            row[1] = u.getName();
            row[2] = u.getAge();
            model.addRow(row);
}
       clearFields();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }    
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formTitleLable = new javax.swing.JLabel();
        firstnameLable = new javax.swing.JLabel();
        ageLable = new javax.swing.JLabel();
        photoImg = new javax.swing.JLabel();
        dtLable = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        viewSaveButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(789, 474));

        formTitleLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formTitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitleLable.setText("View Info");

        firstnameLable.setText("Name");

        ageLable.setText("Age");

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NAME", "AGE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        userTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(userTable);
        userTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        viewSaveButton.setText("SAVE");
        viewSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSaveButtonActionPerformed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(formTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(photoImg)
                                    .addComponent(dtLable)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(viewSaveButton)))))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addGap(48, 48, 48)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(firstnameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ageLable)
                                .addGap(62, 62, 62)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(ageTextField))))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(formTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnameLable)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLable)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(editButton))
                        .addGap(21, 21, 21)
                        .addComponent(photoImg)
                        .addGap(69, 69, 69)
                        .addComponent(dtLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSaveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        private void clearFields(){
        
        nameTextField.setText("");
        ageTextField.setText("");
        selectedUser = null;
    }
    
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            int selectedRowIndex = userTable.getSelectedRow();
            

                DefaultTableModel model = (DefaultTableModel) userTable.getModel();              
                selectedUser = users.get(selectedRowIndex);
                DatabaseConnector.deleteUser(selectedUser);
                JOptionPane.showMessageDialog(null, "User Data Deleted","Deleted",JOptionPane.INFORMATION_MESSAGE);
                clearFields();
                populateTable();
            

        }
        catch (IllegalArgumentException e){

            JOptionPane.showMessageDialog(this, e.getMessage(),"CANNOT SELECT",JOptionPane.ERROR_MESSAGE);
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"CANNOT DELETE",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void viewSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSaveButtonActionPerformed
        // TODO add your handling code here:
        try{
            
            if (selectedUser == null){
                throw new IllegalArgumentException("No user to edit");
                
            }
            else{
                User newUser = new User();
                newUser.setName(nameTextField.getText());
                newUser.setAge(Integer.parseInt(ageTextField.getText()));
                DatabaseConnector.editUser(selectedUser,newUser);
                if ((selectedUser.getName().equals(newUser.getName())) && (selectedUser.getAge() == newUser.getAge())){

                    throw new IllegalArgumentException("No changes to existing data");
                }   
                clearFields();
                populateTable();
            }
        
            
        }  
        catch (IllegalArgumentException e){
            if ("No user to edit".equals(e.getMessage().toLowerCase())){
                JOptionPane.showMessageDialog(this, "Select Users to Edit","EDIT Error",JOptionPane.ERROR_MESSAGE);
            }
            
            else{
                JOptionPane.showMessageDialog(this, "Please update data before save.","EDIT Error",JOptionPane.ERROR_MESSAGE);
            }
            
   
        }
    }//GEN-LAST:event_viewSaveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        try{
            
            int selectedRowIndex = userTable.getSelectedRow();
               
            selectedUser = users.get(selectedRowIndex);
            nameTextField.setText(selectedUser.getName());
            ageTextField.setText(String.valueOf(selectedUser.getAge()));
                
            }
        
        catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "EDIT Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLable;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel dtLable;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel firstnameLable;
    private javax.swing.JLabel formTitleLable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel photoImg;
    private javax.swing.JTable userTable;
    private javax.swing.JButton viewSaveButton;
    // End of variables declaration//GEN-END:variables

    
}
