/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.SimpleDateFormat;



/**
 *
 * @author A
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel bottomPanel;
    public FormPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        formTitleLable = new javax.swing.JLabel();
        lastnameLable = new javax.swing.JLabel();
        firstnameLable = new javax.swing.JLabel();
        ageLable = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        patientTypeLable = new javax.swing.JLabel();
        genderLable = new javax.swing.JLabel();
        photoLable = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        anotherRadioButton = new javax.swing.JRadioButton();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        imgPath = new javax.swing.JTextField();
        messageTextLable = new javax.swing.JLabel();
        msgTextField = new javax.swing.JTextField();
        dateLable = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(789, 488));

        formTitleLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formTitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitleLable.setText("Patient Registration Form");

        lastnameLable.setText("Lastname");

        firstnameLable.setText("Firstname");

        ageLable.setText("Age");

        emailLable.setText("E-mail");

        patientTypeLable.setText("Patient Type");

        genderLable.setText("Gender");

        photoLable.setText("Photo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior", "Adult", "Child" }));

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(anotherRadioButton);
        anotherRadioButton.setText("Another");
        anotherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherRadioButtonActionPerformed(evt);
            }
        });

        lastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextFieldActionPerformed(evt);
            }
        });

        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyPressed(evt);
            }
        });

        submitButton.setText("Submmit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Upload Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imgPath.setText("image path");
        imgPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgPathActionPerformed(evt);
            }
        });

        messageTextLable.setText("Message");

        dateLable.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(photoLable)
                            .addComponent(patientTypeLable)
                            .addComponent(genderLable))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maleRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(femaleRadioButton)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anotherRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(imgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(formTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstnameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lastnameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ageLable)
                                .addComponent(emailLable)
                                .addComponent(messageTextLable))
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lastnameTextField)
                                .addComponent(ageTextField)
                                .addComponent(emailTextField)
                                .addComponent(firstnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(msgTextField)))))
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(dateLable))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(formTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLable)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLable)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLable)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLable)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageTextLable)
                    .addComponent(msgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientTypeLable)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLable)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(anotherRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLable)
                    .addComponent(jButton1)
                    .addComponent(imgPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLable)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    private void anotherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anotherRadioButtonActionPerformed

    private void lastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextFieldActionPerformed
//    public User newUser;
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        User newUser = new User();
        newUser.setFirstname(firstnameTextField.getText());
        newUser.setLastname(lastnameTextField.getText());
        
        newUser.setAge(Integer.parseInt(ageTextField.getText()));
       
        // Validate and set the age
    try {
        int age = Integer.parseInt(ageTextField.getText());
        if(age < 0) throw new NumberFormatException("Age cannot be negative");
        newUser.setAge(age);
    } catch (NumberFormatException e) {
        // Handle invalid age input
        JOptionPane.showMessageDialog(this, "Invalid age. Please enter a valid number.");
        return;
    }
        String patientType = (String)jComboBox1.getSelectedItem();
        newUser.setPatientType(patientType);
        
        newUser.setEmail(emailTextField.getText());
        newUser.setMessage(msgTextField.getText());
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String date = sdf.format(jDateChooser1.getDate());
        newUser.setDate(date);
//        newUser.setPhoto(new photo(edited_image));
        
        newUser.setGender(genderButtonGroup.getSelection().getActionCommand());//get radio button
        // Set the gender based on selected radio button
        if (maleRadioButton.isSelected()) {
        newUser.setGender("Male");
        } else if (femaleRadioButton.isSelected()) {
        newUser.setGender("Female");
        } else if (anotherRadioButton.isSelected()) {
        newUser.setGender("Another");
        } else {
        // Handle case where no gender is selected if needed
        JOptionPane.showMessageDialog(this, "Please select a gender.");
        return;
    }
        if (imgPath != null)
        {
            newUser.setPhoto(imgPath.getText());
        }
        else
        {
            
        }

//        newUser.setMessage(messageTextArea.getText());
//        
//        newUser.setPatientType(patientTypeComboBox.getSelectedItem().toString());
//      newUser.setGender(getSelectedGender()); // This requires a method to determine the selected gender from radio buttons
    
        ViewPanel newViewPanel = new ViewPanel(newUser, bottomPanel);
        bottomPanel.add(newViewPanel, "ViewPanel");
        CardLayout layout = (CardLayout)bottomPanel.getLayout();
//        layout.next(bottomPanel,"ViewPanel");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser imgFile = new JFileChooser();
        if (imgFile.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
        {
            try {
                BufferedImage img = ImageIO.read(imgFile.getSelectedFile());
                Image editedImage = img.getScaledInstance(60, 80 , Image.SCALE_SMOOTH);
                if (editedImage != null)
                {
                    imgPath.setText(imgFile.getSelectedFile().getAbsolutePath());
                }
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Wrong Path!");
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imgPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgPathActionPerformed

    private void ageTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyPressed
        // TODO add your handling code here:
        try{
            int age = Integer.parseInt(ageTextField.getText());
            ageTextField.setForeground(Color.black);
        } 
        catch(Exception e){
            ageTextField.setForeground(Color.red);
        }
    }//GEN-LAST:event_ageTextFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLable;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JRadioButton anotherRadioButton;
    private javax.swing.JLabel dateLable;
    private javax.swing.JLabel emailLable;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstnameLable;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel formTitleLable;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLable;
    private javax.swing.JTextField imgPath;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lastnameLable;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel messageTextLable;
    private javax.swing.JTextField msgTextField;
    private javax.swing.JLabel patientTypeLable;
    private javax.swing.JLabel photoLable;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
