/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author A
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    User u;
    JPanel bottomPanel;
    public ViewPanel(User inputUser, JPanel bottomPanel) {
        initComponents();
        this.u = inputUser;
        this.bottomPanel = bottomPanel;
        populateDetails();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formTitleLable = new javax.swing.JLabel();
        lastnameLable = new javax.swing.JLabel();
        firstnameLable = new javax.swing.JLabel();
        ageLable = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        patientTypeLable = new javax.swing.JLabel();
        genderLable = new javax.swing.JLabel();
        photoLable = new javax.swing.JLabel();
        fnLable = new javax.swing.JLabel();
        lnTextLable = new javax.swing.JLabel();
        agLable = new javax.swing.JLabel();
        emLable = new javax.swing.JLabel();
        ptLable = new javax.swing.JLabel();
        gLable = new javax.swing.JLabel();
        photoImg = new javax.swing.JLabel();
        MessageLable = new javax.swing.JLabel();
        msgLable = new javax.swing.JLabel();
        RegistrationDateLable = new javax.swing.JLabel();
        dtLable = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(789, 474));

        formTitleLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formTitleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitleLable.setText("View Info");

        lastnameLable.setText("Lastname");

        firstnameLable.setText("Firstname");

        ageLable.setText("Age");

        emailLable.setText("E-mail");

        patientTypeLable.setText("Patient Type");

        genderLable.setText("Gender");

        photoLable.setText("photo");

        MessageLable.setText("Message");

        RegistrationDateLable.setText("Registration Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoLable)
                        .addGap(33, 33, 33)
                        .addComponent(photoImg))
                    .addComponent(ageLable)
                    .addComponent(emailLable)
                    .addComponent(genderLable)
                    .addComponent(MessageLable)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegistrationDateLable)
                        .addGap(49, 49, 49)
                        .addComponent(dtLable))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstnameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastnameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(agLable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(emLable, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnTextLable, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fnLable, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientTypeLable)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gLable, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptLable, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(formTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(formTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLable)
                    .addComponent(lnTextLable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientTypeLable)
                    .addComponent(ptLable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLable)
                    .addComponent(gLable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLable)
                    .addComponent(photoImg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MessageLable)
                    .addComponent(msgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrationDateLable)
                    .addComponent(dtLable))
                .addGap(18, 50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MessageLable;
    private javax.swing.JLabel RegistrationDateLable;
    private javax.swing.JLabel agLable;
    private javax.swing.JLabel ageLable;
    private javax.swing.JLabel dtLable;
    private javax.swing.JLabel emLable;
    private javax.swing.JLabel emailLable;
    private javax.swing.JLabel firstnameLable;
    private javax.swing.JLabel fnLable;
    private javax.swing.JLabel formTitleLable;
    private javax.swing.JLabel gLable;
    private javax.swing.JLabel genderLable;
    private javax.swing.JLabel lastnameLable;
    private javax.swing.JLabel lnTextLable;
    private javax.swing.JLabel msgLable;
    private javax.swing.JLabel patientTypeLable;
    private javax.swing.JLabel photoImg;
    private javax.swing.JLabel photoLable;
    private javax.swing.JLabel ptLable;
    // End of variables declaration//GEN-END:variables

    private void populateDetails() {
    //    firstnameTextField.setText(u.getFirstname());
    //    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    if (u != null) {
        // Assuming you have JLabels for displaying the user details
//        firstnameTextField.setText(u.getFirstname()); // Example for setting text of a JLabel
//        lastnameTextField.setText(u.getLastname());
//        ageTextField.setText(String.valueOf(u.getAge())); // Convert int to String
//        emailTextField.setText(u.getEmail());
//        // Similar for other details like patientType and gender
//        // For gender, you might directly set the text of a JLabel
//        genderTextField.setText(u.getGender());
//        // If patientType is to be displayed in a JLabel or a non-editable JTextField
//        patientTypeTextField.setText(u.getPatientType());
//        
//        // Handling the photo if you have an ImageIcon or similar for displaying images
////        if (u.getPhoto() != null) {
//            // Assuming photoLabel is a JLabel meant to display the user's photo
////            ImageIcon photoIcon = new ImageIcon(u.getPhoto()); // You might need to convert Image to ImageIcon
////            photoLabel.setIcon(photoIcon);
          fnLable.setText(u.getFirstname());
          lnTextLable.setText(u.getLastname());
          agLable.setText(String.valueOf(u.getAge()));
          emLable.setText(u.getEmail());
          gLable.setText(u.getGender());
          ptLable.setText(u.getPatientType());
          msgLable.setText(u.getMessage());
          dtLable.setText(u.getDate());
          if (u != null && u.getPhoto() != null) {
//              ImageIcon icon = new ImageIcon(u.getPhoto()); // Wrap the Image for display
//              photoLable.setIcon(icon); // Resize as necessary
            try {
                BufferedImage img = ImageIO.read(new File(u.getPhoto()));
                Image editedImage = img.getScaledInstance(60, 80 , Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(editedImage);
                photoImg.setIcon(icon);
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "can't read image");
                ex.printStackTrace();
            }
            
    }
//        }
    } else {
        // Optionally handle the case where the user object is null
        System.out.println("User object is null, cannot populate details.");
    }
    }
}
